test:
	@check-jsonschema --schemafile WorkflowRunStateChange/WorkflowRunStateChange.schema.json WorkflowRunStateChange/examples/WRSC__example1.json
	@check-jsonschema --schemafile WorkflowRunStateChange/WorkflowRunStateChange.schema.json WorkflowRunStateChange/examples/WRSC__example2.json
	@check-jsonschema --schemafile AnalysisRunStateChange/AnalysisRunStateChange.schema.json AnalysisRunStateChange/examples/ARSC__example1.json
	@check-jsonschema --schemafile AnalysisRunStateChange/AnalysisRunStateChange.schema.json AnalysisRunStateChange/examples/ARSC__example2.json
	@check-jsonschema --schemafile AnalysisRunInitiated/AnalysisRunInitiated.schema.json AnalysisRunInitiated/examples/ARI__example1.json
	@check-jsonschema --schemafile AnalysisRunFinalised/AnalysisRunFinalised.schema.json AnalysisRunFinalised/examples/ARF__example.json
