# generated by datamodel-codegen:
#   filename:  AnalysisRunFinalised.schema.json
#   timestamp: 2025-06-26T07:25:35+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class Readset(BaseModel):
    orcabusId: str
    rgid: str


class Analysis(BaseModel):
    orcabusId: str
    name: str
    version: str


class Library(BaseModel):
    orcabusId: str
    libraryId: str
    readsets: List[Readset]


class AnalysisRunFinalised(BaseModel):
    id: str
    version: str
    timestamp: datetime
    orcabusId: str
    analysisRunName: str
    analysis: Analysis
    libraries: List[Library]
    computeEnv: str
    storageEnv: str


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail-type')
    detail: AnalysisRunFinalised
