# generated by datamodel-codegen:
#   filename:  AnalysisRunInitiated.schema.json
#   timestamp: 2025-05-23T06:45:24+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class Readset(BaseModel):
    orcabusId: str
    rgid: Optional[str] = None
    phenotype: Optional[str] = None


class Analysis(BaseModel):
    orcabusId: str
    name: Optional[str] = None
    version: Optional[str] = None


class Library(BaseModel):
    libraryId: str
    orcabusId: str
    readsets: Optional[List[Readset]] = None


class AnalysisRunInitiated(BaseModel):
    timestamp: datetime
    analysisRunName: str
    analysis: Analysis
    libraries: List[Library]
    computeEnv: Optional[str] = None
    storageEnv: Optional[str] = None


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail-type')
    detail: AnalysisRunInitiated
