# generated by datamodel-codegen:
#   filename:  AnalysisRunStateChange.schema.json
#   timestamp: 2025-05-20T08:42:18+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class Library(BaseModel):
    libraryId: str
    orcabusId: str


class Readset(BaseModel):
    orcabusId: str
    rgid: Optional[str] = None
    phenotype: Optional[str] = None


class Analysis(BaseModel):
    orcabusId: str
    name: Optional[str] = None
    version: Optional[str] = None


class AnalysisRunStateChange(BaseModel):
    orcabusId: str
    timestamp: datetime
    status: str
    analysisRunName: str
    analysis: Analysis
    libraries: Optional[List[Library]] = None
    readsets: Optional[List[Readset]] = None


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail-type')
    detail: AnalysisRunStateChange
