# generated by datamodel-codegen:
#   filename:  AnalysisRunUpdate.schema.json
#   timestamp: 2026-04-02T04:07:56+00:00

from __future__ import annotations
from pydantic import BaseModel, Field
from datetime import datetime


class Readset(BaseModel):
    orcabusId: str
    rgid: str


class Analysis(BaseModel):
    orcabusId: str
    name: str
    version: str


class Library(BaseModel):
    orcabusId: str
    libraryId: str
    readsets: list[Readset] | None = None


class AnalysisRunUpdate(BaseModel):
    id: str | None = None
    version: str | None = None
    timestamp: datetime | None = None
    orcabusId: str | None = None
    analysisRunName: str
    analysis: Analysis
    libraries: list[Library]
    computeEnv: str | None = None
    storageEnv: str | None = None
    status: str


class AWSEvent(BaseModel):
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: AnalysisRunUpdate
