# generated by datamodel-codegen:
#   filename:  WorkflowRunStateChange.schema.json
#   timestamp: 2025-05-23T06:45:22+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class LibraryRecord(BaseModel):
    libraryId: str
    orcabusId: str


class AnalysisRun(BaseModel):
    orcabusId: str
    name: Optional[str] = None


class Workflow(BaseModel):
    orcabusId: str
    name: Optional[str] = None
    version: Optional[str] = None


class Payload(BaseModel):
    refId: str
    version: str
    data: Dict[str, Any]


class Analysis(BaseModel):
    __root__: Any


class WorkflowRunStateChange(BaseModel):
    orcabusId: Optional[str] = None
    portalRunId: str
    timestamp: datetime
    status: str
    workflow: Optional[Workflow] = None
    workflowName: str
    workflowVersion: str
    workflowRunName: str
    analysisRun: Optional[Analysis] = None
    linkedLibraries: Optional[List[LibraryRecord]] = None
    payload: Optional[Payload] = None


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail-type')
    detail: WorkflowRunStateChange
