# generated by datamodel-codegen:
#   filename:  WorkflowRunStateChange.schema.json
#   timestamp: 2025-08-28T09:25:03+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Readset(BaseModel):
    orcabusId: str
    rgid: str


class Workflow(BaseModel):
    orcabusId: str
    name: str
    version: str
    codeVersion: str
    executionEngine: str
    executionEnginePipelineId: Optional[str] = None
    validationState: Optional[str] = None


class AnalysisRun(BaseModel):
    orcabusId: str
    name: str


class Payload(BaseModel):
    orcabusId: str
    refId: str
    version: str
    data: Dict[str, Any]


class Library(BaseModel):
    libraryId: str
    orcabusId: str
    readsets: Optional[List[Readset]] = None


class WorkflowRunStateChange(BaseModel):
    id: str
    version: str
    timestamp: datetime
    orcabusId: str
    portalRunId: str
    workflowRunName: str
    workflow: Workflow
    analysisRun: Optional[AnalysisRun] = None
    libraries: Optional[List[Library]] = None
    computeEnv: Optional[str] = None
    storageEnv: Optional[str] = None
    status: str
    payload: Optional[Payload] = None


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail-type')
    detail: WorkflowRunStateChange
