# generated by datamodel-codegen:
#   filename:  WorkflowRunStateChange.schema.json
#   timestamp: 2026-04-02T05:20:39+00:00

from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Any
from datetime import datetime


class Readset(BaseModel):
    orcabusId: str
    rgid: str


class Workflow(BaseModel):
    orcabusId: str
    name: str
    version: str
    codeVersion: str
    executionEngine: str
    executionEnginePipelineId: str | None = None
    validationState: str | None = None


class AnalysisRun(BaseModel):
    orcabusId: str
    name: str


class Payload(BaseModel):
    orcabusId: str
    refId: str
    version: str
    data: dict[str, Any]


class Library(BaseModel):
    libraryId: str
    orcabusId: str
    readsets: list[Readset] | None = None


class WorkflowRunStateChange(BaseModel):
    id: str
    version: str
    timestamp: datetime
    orcabusId: str
    portalRunId: str
    workflowRunName: str
    workflow: Workflow
    analysisRun: AnalysisRun | None = None
    libraries: list[Library] | None = None
    computeEnv: str | None = None
    storageEnv: str | None = None
    status: str
    payload: Payload | None = None


class AWSEvent(BaseModel):
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: WorkflowRunStateChange
