# generated by datamodel-codegen:
#   filename:  WorkflowRunUpdate.schema.json
#   timestamp: 2026-05-28T08:52:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class Readset(BaseModel):
    orcabusId: str
    rgid: str


class Workflow(BaseModel):
    orcabusId: str
    name: str | None = None
    version: str | None = None
    codeVersion: str | None = None
    executionEngine: str | None = None
    executionEnginePipelineId: str | None = None
    validationState: str | None = None


class AnalysisRun(BaseModel):
    orcabusId: str
    name: str


class Payload(BaseModel):
    refId: str | None = None
    version: str
    data: dict[str, Any]


class Library(BaseModel):
    libraryId: str
    orcabusId: str
    readsets: list[Readset] | None = None


class WorkflowRunUpdate(BaseModel):
    id: str | None = None
    version: str | None = None
    timestamp: AwareDatetime | None = None
    orcabusId: str | None = None
    portalRunId: str
    executionId: str | None = None
    workflowRunName: str
    workflow: Workflow
    analysisRun: AnalysisRun | None = None
    libraries: list[Library]
    computeEnv: str | None = None
    storageEnv: str | None = None
    status: str
    payload: Payload | None = None


class AWSEvent(BaseModel):
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: AwareDatetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias='detail-type')
    detail: WorkflowRunUpdate
