# Generated by Django 5.2 on 2025-06-03 05:27

import django.db.models.deletion
import workflow_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0003_alter_analysis_orcabus_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrun",
            name="status",
        ),
        migrations.CreateModel(
            name="AnalysisRunReadset",
            fields=[
                (
                    "orcabus_id",
                    workflow_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("library_id", models.CharField(max_length=255)),
                ("library_oid", models.CharField(max_length=255)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readsets",
                        to="workflow_manager.analysisrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnalysisRunState",
            fields=[
                (
                    "orcabus_id",
                    workflow_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="workflow_manager.analysisrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("analysis_run", "status", "timestamp")},
            },
        ),
    ]
