# Generated by Django 5.2.3 on 2025-07-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow_manager",
            "0004_remove_analysisrun_status_analysisrunreadset_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together={("workflow_name", "workflow_version", "execution_engine")},
        ),
    ]
