# Generated by Django 5.2.3 on 2025-07-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0005_alter_workflow_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="analysiscontext",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysiscontext",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=255,
            ),
        ),
    ]
