# Generated by Django 5.2.4 on 2025-08-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0007_alter_workflow_execution_engine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="execution_engine",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("ICA", "Ica"),
                    ("SEQERA", "Seqera"),
                    ("AWS_BATCH", "Aws Batch"),
                    ("AWS_ECS", "Aws Ecs"),
                    ("AWS_EKS", "Aws Eks"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="execution_engine_pipeline_id",
            field=models.CharField(max_length=255),
        ),
    ]
