# Generated by Django 5.2.4 on 2025-08-14 09:24

import workflow_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0010_workflowruncontext_workflowrun_contexts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Readset",
            fields=[
                (
                    "orcabus_id",
                    workflow_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("rgid", models.CharField(max_length=255)),
                ("library_id", models.CharField(max_length=255)),
                ("library_orcabus_id", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="readsets",
            field=models.ManyToManyField(to="workflow_manager.readset"),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="readsets",
            field=models.ManyToManyField(to="workflow_manager.readset"),
        ),
        migrations.DeleteModel(
            name="AnalysisRunReadset",
        ),
    ]
