# Generated by Django 5.2.4 on 2025-08-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow_manager",
            "0011_readset_analysisrun_readsets_workflowrun_readsets_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="validation_state",
            field=models.CharField(
                choices=[
                    ("UNVALIDATED", "Unvalidated"),
                    ("VALIDATED", "Validated"),
                    ("DEPRECATED", "Deprecated"),
                    ("FAILED", "Failed"),
                ],
                default="VALIDATED",
                max_length=255,
            ),
        ),
    ]
