# Generated by Django 5.2.4 on 2025-08-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0012_workflow_validation_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrun",
            name="contexts",
        ),
        migrations.AlterUniqueTogether(
            name="workflowruncontext",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workflowrun",
            name="contexts",
        ),
        migrations.DeleteModel(
            name="AnalysisRunContext",
        ),
        migrations.DeleteModel(
            name="WorkflowRunContext",
        ),
    ]
