# Generated by Django 5.2.4 on 2025-08-19 06:43

import workflow_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0013_remove_analysisrun_contexts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunContext",
            fields=[
                (
                    "orcabus_id",
                    workflow_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "usecase",
                    models.CharField(
                        choices=[("COMPUTE", "Compute"), ("STORAGE", "Storage")],
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "usecase")},
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="contexts",
            field=models.ManyToManyField(to="workflow_manager.runcontext"),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="contexts",
            field=models.ManyToManyField(to="workflow_manager.runcontext"),
        ),
    ]
