# Generated by Django 5.2.4 on 2025-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow_manager",
            "0014_runcontext_analysisrun_contexts_workflowrun_contexts",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysiscontext",
            name="usecase",
            field=models.CharField(
                choices=[("COMPUTE", "Compute"), ("STORAGE", "Storage")], max_length=255
            ),
        ),
    ]
