# Generated by Django 5.2.4 on 2025-08-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0015_alter_analysiscontext_usecase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflow",
            old_name="workflow_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="workflow",
            old_name="workflow_version",
            new_name="version",
        ),
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together={("name", "version", "execution_engine")},
        ),
    ]
