# Generated by Django 5.2.4 on 2025-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0016_rename_workflow_name_workflow_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workflow",
            name="code_version",
            field=models.CharField(default="0.0.0", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="workflow",
            unique_together={("name", "version", "code_version", "execution_engine")},
        ),
    ]
