# Generated by Django 5.2.4 on 2025-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow_manager",
            "0017_alter_workflow_unique_together_workflow_code_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="execution_engine_pipeline_id",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
