# Generated by Django 5.2.4 on 2025-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0018_alter_workflow_execution_engine_pipeline_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="validation_state",
            field=models.CharField(
                choices=[
                    ("UNVALIDATED", "Unvalidated"),
                    ("VALIDATED", "Validated"),
                    ("DEPRECATED", "Deprecated"),
                    ("FAILED", "Failed"),
                ],
                default="UNVALIDATED",
                max_length=255,
            ),
        ),
    ]
