# Generated by Django 5.2.7 on 2025-11-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0019_alter_workflow_validation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysiscontext",
            name="usecase",
            field=models.CharField(
                choices=[("VALIDATION", "Validation"), ("APPROVAL", "Approval")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="validation_state",
            field=models.CharField(
                choices=[
                    ("UNVALIDATED", "Unvalidated"),
                    ("VERIFIED", "Verified"),
                    ("VALIDATED", "Validated"),
                    ("FAILED", "Failed"),
                    ("DEPRECATED", "Deprecated"),
                ],
                default="UNVALIDATED",
                max_length=255,
            ),
        ),
    ]
