# Generated by Django 5.2.10 on 2026-02-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0019_alter_workflow_validation_state"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkflowRunComment",
            new_name="Comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="text",
        ),
    ]
