# Generated by Django 5.2.10 on 2026-02-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow_manager",
            "0020_rename_workflowruncomment_to_comment_and_comment_field_to_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="analysis_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="workflow_manager.analysisrun",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="workflow_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="workflow_manager.workflowrun",
            ),
        ),
    ]
