# Generated by Django 5.2.12 on 2026-03-23 07:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0021_comment_analysis_run_alter_comment_workflow_run"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="runcontext",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="runcontext",
            name="data",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="runcontext",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ICAV2", "Icav2"),
                    ("SEQERA", "Seqera"),
                    ("AWS_BATCH", "Aws Batch"),
                    ("AWS_ECS", "Aws Ecs"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="runcontext",
            name="usecase",
            field=models.CharField(
                choices=[
                    ("COMPUTE", "Compute"),
                    ("STORAGE", "Storage"),
                    ("EXECUTION_MODE", "Execution Mode"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="runcontext",
            constraint=models.UniqueConstraint(
                fields=("name", "usecase", "platform"),
                name="unique_runcontext_name_usecase_platform",
                nulls_distinct=False,
            ),
        ),
    ]
