# Generated by Django 5.2.12 on 2026-03-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0022_comment_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payload",
            name="payload_ref_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="payload",
            unique_together={("payload_ref_id", "version")},
        ),
    ]
