# Generated by Django 5.2.12 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0023_alter_payload_payload_ref_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="created_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
